apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-spring-users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
