apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-user-app
  labels:
    app: spring-boot-user
  annotations:
    description: "This is the server for the users microservice."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-user-app
  template:
    metadata:
      labels:
        app: spring-boot-user-app
    spec:
      containers:
        - name: spring-boot-user-app
          image: emilykodocker/spring-bitware-users:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/mydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
