apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - port: 8080        # Puerto en el cual la aplicación escucha dentro del contenedor
      targetPort: 8080   # Puerto del contenedor
  type: ClusterIP        # Tipo de servicio, se puede cambiar a LoadBalancer si se necesita acceso externo
